api_platform:
    title: Querify
    version: 1.0.0
#    swagger:
#        versions: [ 3 ]
#        api_keys:
#            JWT:
#                name: Authorization
#                type: header
#    defaults:
#        stateless: true
#        cache_headers:
#            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Infrastructure/Api/Resource'
    formats:
        json: [ 'application/json' ]
