doctrine:
    dbal:
        driver: 'pdo_psql'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf_8_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Querify:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/'
                prefix: 'Querify\Domain'
