services:
  http_client.default:
    alias: 'http_client'

  http_client.slack:
    class: Symfony\Component\HttpClient\CurlHttpClient
    arguments:
      - { base_uri: 'https://slack.com/api' }

  http_client.google:
    class: Symfony\Component\HttpClient\CurlHttpClient
    arguments:
      - { base_uri: 'https://www.googleapis.com' }