framework:
    messenger:
        failure_transport: failed
        default_bus: app.command_bus

        buses:
            app.command_bus:
                middleware:
                    - doctrine_transaction
            app.domain_event_bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_transaction
            app.query_bus: ~

        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%messages'
             failed: '%env(MESSENGER_TRANSPORT_DSN)%failed'
             sync: 'sync://'

        routing:
            Demandify\Application\Command\ExecuteDemand\ExecuteDemand: async
            Demandify\Application\Command\UpdateSentNotificationsWithDecision\UpdateSentNotificationsWithDecision: async
            Demandify\Application\Command\SendDemandNotification\SendDemandNotification: async
            Demandify\Domain\User\Event\UserRegistered: async
            Demandify\Domain\Demand\Event\DemandApproved: async
            Demandify\Domain\Demand\Event\DemandDeclined: async
            Demandify\Domain\Demand\Event\DemandSubmitted: async


when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
