framework:
    messenger:
        failure_transport: failed

        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%messages'
             failed: '%env(MESSENGER_TRANSPORT_DSN)%failed'
             sync: 'sync://'

        routing:
            Querify\Domain\User\Event\UserRegistered: async
            Querify\Domain\Demand\Event\DemandSubmitted: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
