framework:
    messenger:
        failure_transport: failed
        default_bus: command_bus

        buses:
            command_bus:
                middleware:
                    - doctrine_transaction
            domain_event_bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_transaction
            query_bus:
                default_middleware: allow_no_handlers

        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%messages'
             failed: '%env(MESSENGER_TRANSPORT_DSN)%failed'
             notification: '%env(MESSENGER_TRANSPORT_DSN)%notification'
             task: '%env(MESSENGER_TRANSPORT_DSN)%task'
             sync: 'sync://'

        routing:
            # Command
            Demandify\Application\Command\ApproveDemand\ApproveDemand: async
            Demandify\Application\Command\DeclineDemand\DeclineDemand: async
            Demandify\Application\Command\ExecuteDemand\ExecuteDemand: task
            Demandify\Application\Command\LinkSocialAccountToUser\LinkSocialAccountToUser: async
            Demandify\Application\Command\SaveSentNotification\SaveSentNotification: async
            Demandify\Application\Command\SendDemandNotification\SendDemandNotification: async
            Demandify\Application\Command\SubmitDemand\SubmitDemand: async
            Demandify\Application\Command\UpdateEligibleApprovers\UpdateEligibleApprovers: async
            Demandify\Application\Command\UpdateSentNotificationsWithDecision\UpdateSentNotificationsWithDecision: async
            Demandify\Application\Command\UpdateSocialAccountNotifiability\UpdateSocialAccountNotifiability: sync
            # Event
            Demandify\Domain\Demand\Event\DemandApproved: async
            Demandify\Domain\Demand\Event\DemandDeclined: async
            Demandify\Domain\Demand\Event\DemandSubmitted: async
            Demandify\Domain\Task\Event\TaskFailed: async
            Demandify\Domain\Task\Event\TaskSucceeded: async
            # Query
            Demandify\Application\Query\GetDemandsSubmittedByUser\GetDemandsSubmittedByUser: sync
            Demandify\Application\Query\GetDemandsToBeReviewedForUser\GetDemandsToBeReviewedForUser: sync
            Demandify\Application\Query\IsUserEligibleToDecisionForExternalService\IsUserEligibleToDecisionForExternalService: sync
            # Symfony
            Symfony\Component\Notifier\Message\ChatMessage: notification

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
                notification: 'in-memory://'
                task: 'in-memory://'