services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: querify
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "querify", "-U", "postgres"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  session:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - session:/data

  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - database
      - rabbitmq
      - session
    networks:
      - default

  nginx:
    build: docker/nginx
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/etc/nginx/ssl
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
volumes:
  database_data:
  rabbitmq_data:
  session:

networks:
  default:
    driver: bridge