#!/usr/bin/env bash

source docker/terminal-utils

pretty_print_section "starting containers"
docker-compose up -d

pretty_print_section "wait for database"
source ./docker/wait-for-container
waitContainer "database"

pretty_print_section "wait for database"
source ./docker/wait-for-container
waitContainer "rabbitmq"

pretty_print_section "install dependencies"
docker-compose exec php composer install --no-cache

pretty_print_section "create database if not exist"
docker-compose exec php bin/console doctrine:database:create --if-not-exists

pretty_print_section "delete & create test database"
docker-compose exec php bin/console doctrine:database:drop --force --env=test
docker-compose exec php bin/console doctrine:database:create --env=test --if-not-exists

pretty_print_section "execute migrations"
docker-compose exec php bin/console doctrine:migrations:migrate --no-interaction

pretty_print_section "execute test migrations"
docker-compose exec php bin/console doctrine:migrations:migrate --env=test --no-interaction

pretty_print_section "setup transports"
docker-compose exec php bin/console messenger:setup-transports

pretty_print_section "starting consumers"
docker/start-consumers





