controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: Demandify\Infrastructure\Controller
    type: attribute

api_login_check:
    path: /api/login

app_logout:
    path: /logout
    methods: GET


