imports:
    - { resource: packages/http_clients.yaml }

parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $slackApiHttpClient: '@http_client.slack'
            $googleApiHttpClient: '@http_client.google'

    _instanceof:
        Demandify\Infrastructure\Authentication\OAuth2\Provider\OAuth2Client:
            tags: [ 'demandify.oauth.client' ]

        Demandify\Infrastructure\Notification\Client\NotificationClient:
            tags: [ 'demandify.notification.client' ]

        Demandify\Infrastructure\Webhook\WebhookHandler:
            tags: [ 'demandify.webhook.handler' ]

    Demandify\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Demandify\Infrastructure\Authentication\OAuth2\Provider\OAuth2ClientResolver:
        arguments:
            - !tagged_iterator 'demandify.oauth.client'

    Demandify\Infrastructure\Notification\NotificationClientResolver:
        arguments:
            - !tagged_iterator 'demandify.notification.client'

    Demandify\Infrastructure\Controller\WebhookController:
        arguments:
            - !tagged_iterator 'demandify.webhook.handler'

when@dev:
    services:
        Demandify\Infrastructure\Doctrine\Listener\RemoveCreateSchemaFromMigrationListener:
            tags:
                - { name: doctrine.event_listener, event: postGenerateSchema }