imports:
    - { resource: packages/http_clients.yaml }

parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $slackApiHttpClient: '@logging_http_client.slack'
            $googleApiHttpClient: '@logging_http_client.google'

    _instanceof:
        Demandify\Application\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: app.command_bus }

        Demandify\Application\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: app.query_bus }

        Demandify\Application\Event\DomainEventHandler:
            tags:
                - { name: messenger.message_handler, bus: app.domain_event_bus }

        Demandify\Infrastructure\Authentication\OAuth2\Provider\OAuth2Client:
            tags: [ 'demandify.oauth.client' ]

        Demandify\Infrastructure\Notification\Options\NotificationOptionsFactory:
            tags: [ 'demandify.notification_options.factory' ]

        Demandify\Infrastructure\Webhook\WebhookHandler:
            tags: [ 'demandify.webhook.handler' ]

    Demandify\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Demandify\Infrastructure\Authentication\OAuth2\Provider\OAuth2ClientResolver:
        arguments:
            - !tagged_iterator 'demandify.oauth.client'

    Demandify\Infrastructure\Notification\NotificationOptionsFactory:
        arguments:
            - !tagged_iterator 'demandify.notification_options.factory'

    Demandify\Infrastructure\Controller\WebhookController:
        arguments:
            - !tagged_iterator 'demandify.webhook.handler'

when@dev:
    services:
        Demandify\Infrastructure\Doctrine\Listener\RemoveCreateSchemaFromMigrationListener:
            tags:
                - { name: doctrine.event_listener, event: postGenerateSchema }