parameters:


services:
    _instanceof:
        Querify\Infrastructure\ExternalServices\OAuth\OAuthHandler:
            tags: [ 'querify.oauth.handler' ]
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $slackApiHttpClient: '@http_client.slack'

    Querify\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Querify\Infrastructure\ExternalServices\OAuth\OAuthManager:
        arguments:
            - !tagged_iterator 'querify.oauth.handler'

    http_client.default:
        alias: 'http_client'

    http_client.slack:
        class: Symfony\Component\HttpClient\CurlHttpClient
        arguments:
            - { base_uri: 'https://slack.com/api' }

