imports:
    - { resource: packages/http_clients.yaml }
parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $slackApiHttpClient: '@http_client.slack'

    _instanceof:
        Querify\Infrastructure\Authentication\OAuth2\OAuth2Client:
            tags: [ 'querify.oauth.client' ]

    Querify\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Querify\Infrastructure\Authentication\OAuth2\OAuth2ClientManager:
        arguments:
            - !tagged_iterator 'querify.oauth.client'

when@dev:
    services:
        Querify\Infrastructure\Doctrine\Listener\RemoveCreateSchemaFromMigrationListener:
            tags:
                - { name: doctrine.event_listener, event: postGenerateSchema }