name: ci/cd

on:
  push:
    branches:
      - master
  pull_request:
    master:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  phpunit:
    runs-on: ubuntu-latest
    needs: build_and_push
    services:
      database:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: querify_test
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run PHPUnit tests
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm \
            -e DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/querify?serverVersion=16&charset=utf8" \
            --network="host" \
            ghcr.io/${{ github.repository }}:latest \
            /bin/sh -c "bin/console d:d:c --env=test && bin/console d:m:m --env=test --no-interaction && composer phpunit"

  phpstan:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run PHPStan analysis
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer phpstan

  csfixer:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run CSFixer checks
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer csfixer-check

  deptrac:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run Deptrac analysis
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer deptrac
