name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    master:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  phpunit:
    runs-on: ubuntu-latest
    needs: build_and_push
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: querify
          POSTGRES_PASSWORD: querify
          POSTGRES_DB: querify_test
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHPUnit tests
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm --link postgres:postgres ghcr.io/${{ github.repository }}:latest composer phpunit

  phpspec:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PHPSpec tests
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer phpspec

  phpstan:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PHPStan analysis
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer phpstan

  csfixer:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run CSFixer checks
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer csfixer-check

  deptrac:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Deptrac analysis
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer deptrac