name: ci/cd

on:
  push:
    branches:
      - master
  pull_request:
    master:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  phpunit:
    runs-on: ubuntu-latest
    needs: build_and_push
    services:
      database:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: demandify_test
        ports:
          - 5432:5432
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run PHPUnit tests
        run: |
          mkdir -p coverage
          chmod 777 coverage
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm \
            -e DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/demandify?serverVersion=16&charset=utf8" \
            --network="host" \
            -v ${{ github.workspace }}/coverage:/var/www/html/coverage \
            ghcr.io/${{ github.repository }}:latest \
            /bin/sh -c "bin/console d:d:c --env=test && bin/console d:m:m --env=test --no-interaction && ./vendor/bin/phpunit --coverage-clover coverage/coverage.xml"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage/coverage.xml

  phpstan:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run PHPStan analysis
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer phpstan

  csfixer:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run CSFixer checks
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer csfixer-check

  deptrac:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        id: login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.ACTOR }} --password-stdin

      - name: Run Deptrac analysis
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --rm ghcr.io/${{ github.repository }}:latest composer deptrac
